# Site settings
title: Brian Edmond
email: brianwedmond@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I'm an artist, a worker, an out-of-the-box thinker.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://brianedmond.com" # the base hostname & protocol for your site
github_username:  bedmond
linkedin_username: brian-edmond
permalink: /:title

# Collections
collections:
  portfolio:
    output: true

# Scripts
google_analytics: "UA-72618431-1"

# Build settings
markdown: kramdown
